return {
    pl = {
        config_loader_missing = "Nie znaleziono loadera konfiguracji EXP: %s",
        config_load_failed = "Nie zaladowano konfiguracji EXP: %s",
        rules_loaded = "Zaladowano %d regul EXP z %s.",
        diag_enabled = "Diagnostyka wlaczona.",
        combat_diag_state = "Szczegolowe logi walki: %s.",
        summary_diag_state = "Podsumowanie diagnostyczne co %d s: %s.",
        state_enabled = "wlaczone",
        state_disabled = "wylaczone",
        config_warning = "Ostrzezenie konfiguracji: %s",
        cache_refresh_scenario = "Odswiezam cache scenariusza: %s",
        cache_refresh_player = "Odswiezam cache gracza: %s",
        reason_new_pawn = "wykryto nowy pawn gracza",
        reason_new_player_state = "wykryto nowy player state",
        reason_new_scenario_component = "wykryto nowy scenario component",
        reason_missing_world_context = "brak world context",
        reason_oninit_failed = "OnInit nie powiodlo sie",
        reason_onexec_failed = "OnExec nie powiodlo sie",
        pawn_changed = "Pawn gracza zmieniony: %s -> %s",
        player_state_changed = "PlayerState zmieniony: %s -> %s",
        scenario_component_changed = "Komponent scenariusza zmieniony: %s -> %s",
        scenario_executor_changed = "Executor scenariusza zmieniony: %s -> %s",
        scenario_graph_changed = "Graf scenariusza zmieniony: %s -> %s",
        grant_request = "Zadanie dodania EXP: ilosc=%s powod=%s world=%s",
        world_context_retry = "Ponowne wyszukiwanie world context: %s",
        missing_world_context = "UR5ScenarioTask_AddExp: brak world context.",
        missing_task_class = "UR5ScenarioTask_AddExp: brak klasy taska.",
        using_task_class = "Uzywana klasa taska: %s",
        missing_live_context = "UR5ScenarioTask_AddExp: brak live task class albo world context.",
        task_construct_failed = "UR5ScenarioTask_AddExp: StaticConstructObject nie utworzyl taska.",
        exp_field_failed = "Nie ustawiono pola exp w UR5ScenarioTask_AddExp: %s",
        prepared_task = "Przygotowano task AddExp target=%s graph=%s executor=%s",
        oninit_failed = "UR5ScenarioTask_AddExp: OnInit nie powiodlo sie: %s",
        onexec_failed = "UR5ScenarioTask_AddExp: OnExec nie powiodlo sie: %s",
        exp_awarded = "EXP: +%d za %s.",
        skip_invalid_target = "Pomijam EXP: nieprawidlowy target dla %s",
        skip_duplicate = "Pomijam duplikat EXP dla %s: %s",
        no_rule = "Brak reguly EXP dla %s: %s",
        no_exp_awarded = "Nie przyznano EXP dla %s target=%s wzorzec=%s ilosc=%s",
        matched_rule = "Dopasowano regule EXP dla %s target=%s wzorzec=%s ilosc=%d",
        blocked_by_caps = "Przyznanie EXP zablokowane limitem dla %s target=%s wzorzec=%s",
        skip_duplicate_fallback = "Pomijam duplikat EXP po kluczu zapasowym dla %s: %s",
        add_exp_error = "Blad podczas dodawania EXP przez %s: %s",
        non_kill_ignored = "Pomijam obrazenia bez zabicia z %s",
        kill_received = "Otrzymano obrazenia zabijajace z %s target=%s",
        damage_instance = "Instancja obrazen z %s target=%s zabicie=%s",
        death_component_update = "Aktualizacja komponentu smierci dla %s",
        death_component_ignored = "Pominieto aktualizacje komponentu smierci, bo bDead=false",
        hook_active = "Hook aktywny: %s",
        hook_unavailable = "Hook niedostepny: %s / %s",
        hook_disabled = "Hook wylaczony przez konfiguracje: %s",
        prewarm_retry = "Prewarm: obiekty jeszcze nie dostepne, nastepna proba za %d ms.",
        prewarm_complete = "Prewarm: wszystkie obiekty zbuforowane.",
        build_loaded = "Build %s zaladowany.",
        diag_ready = "Diagnostyka gotowa.",
        diag_summary = "Podsumowanie diag: kill=%d nonkill=%d prob=%d sukces=%d duplikaty=%d cap=%d bledy=%d",
        cap_level_reached = "EXP pominiety: level cap %d osiagniety (%d).",
        cap_level_cut = "EXP uciety do level cap %d: %d -> %d za %s.",
        cap_talent_reached = "EXP pominiety: talent cap %d osiagniety (%d %s).",
        unknown = "nieznany",
    },
    en = {
        config_loader_missing = "EXP config loader not found: %s",
        config_load_failed = "EXP config was not loaded: %s",
        rules_loaded = "Loaded %d EXP rules from %s.",
        diag_enabled = "Diagnostic logging enabled.",
        combat_diag_state = "Verbose combat diagnostics: %s.",
        summary_diag_state = "Diagnostic summary every %d s: %s.",
        state_enabled = "enabled",
        state_disabled = "disabled",
        config_warning = "Config warning: %s",
        cache_refresh_scenario = "Refreshing scenario cache: %s",
        cache_refresh_player = "Refreshing player cache: %s",
        reason_new_pawn = "detected new player pawn",
        reason_new_player_state = "detected new player state",
        reason_new_scenario_component = "detected new scenario component",
        reason_missing_world_context = "missing world context",
        reason_oninit_failed = "OnInit failed",
        reason_onexec_failed = "OnExec failed",
        pawn_changed = "Player pawn changed: %s -> %s",
        player_state_changed = "Player state changed: %s -> %s",
        scenario_component_changed = "Scenario component changed: %s -> %s",
        scenario_executor_changed = "Scenario executor changed: %s -> %s",
        scenario_graph_changed = "Scenario graph changed: %s -> %s",
        grant_request = "EXP grant requested: amount=%s reason=%s world=%s",
        world_context_retry = "Retried world context lookup: %s",
        missing_world_context = "UR5ScenarioTask_AddExp: missing world context.",
        missing_task_class = "UR5ScenarioTask_AddExp: task class missing.",
        using_task_class = "Using task class: %s",
        missing_live_context = "UR5ScenarioTask_AddExp: missing live task class or world context.",
        task_construct_failed = "UR5ScenarioTask_AddExp: StaticConstructObject failed to create task.",
        exp_field_failed = "Failed to set exp field in UR5ScenarioTask_AddExp: %s",
        prepared_task = "Prepared AddExp task target=%s graph=%s executor=%s",
        oninit_failed = "UR5ScenarioTask_AddExp: OnInit failed: %s",
        onexec_failed = "UR5ScenarioTask_AddExp: OnExec failed: %s",
        exp_awarded = "EXP: +%d for %s.",
        skip_invalid_target = "Skipping EXP because target is invalid for %s",
        skip_duplicate = "Skipping duplicate EXP award for %s: %s",
        no_rule = "No EXP rule for %s: %s",
        no_exp_awarded = "No EXP awarded for %s target=%s pattern=%s amount=%s",
        matched_rule = "Matched EXP rule for %s target=%s pattern=%s amount=%d",
        blocked_by_caps = "EXP award blocked by caps for %s target=%s pattern=%s",
        skip_duplicate_fallback = "Skipping duplicate EXP award after fallback key for %s: %s",
        add_exp_error = "Error while adding EXP via %s: %s",
        non_kill_ignored = "Ignoring non-kill damage from %s",
        kill_received = "Kill damage received from %s target=%s",
        damage_instance = "Damage instance from %s target=%s isKill=%s",
        death_component_update = "Death component update for %s",
        death_component_ignored = "Death component update ignored because bDead=false",
        hook_active = "Hook active: %s",
        hook_unavailable = "Hook unavailable: %s / %s",
        hook_disabled = "Hook disabled by config: %s",
        prewarm_retry = "Prewarm: objects not available yet, retrying in %d ms.",
        prewarm_complete = "Prewarm: all objects cached.",
        build_loaded = "Build %s loaded.",
        diag_ready = "Diagnostics ready.",
        diag_summary = "Diag summary: kill=%d nonkill=%d attempts=%d granted=%d duplicates=%d cap=%d errors=%d",
        cap_level_reached = "EXP skipped: level cap %d reached (%d).",
        cap_level_cut = "EXP clamped to level cap %d: %d -> %d for %s.",
        cap_talent_reached = "EXP skipped: talent cap %d reached (%d %s).",
        unknown = "unknown",
    },
}
